### ISSUE TITLE
Adding ProxyCommand to host_config

### ISSUE THREAD

**Issue by BrianMusson** [ParallelSSH/parallel-ssh#106]
The way I establish tunnels today is through the use of a one time use password, so being able to reuse an existing connection by sorting out the proxy command using the ssh config file (like Paramiko does) would be helpful. Appreciate all the hard work!

**Comment by pkittenis** [comment]
Hi there,

Thanks for the interest.

Can you share an example with this use case? I'm interested in seeing what the proxy command used is to see if this can be implemented. If the intention is to just proxy an existing connection that is do-able.

Full `ProxyCommand ` support as in OpenSSH/Paramiko is more complicated as it involves running subprocesses for each tunnel.

**Comment by BrianMusson** [comment]
I open SSH tunnels to all of my bastions (I use a One Time Password token). 
When I SSH to a host, ~/.ssh/config is parsed and matches rules based on the hostmask.

lets say my server list is:
server1.usa.example.com
server2.usa.example.com
server1.can.example.com
server2.can.example.com
server1.mex.example.com
server2.mex.example.com


~/.ssh/config:
# USA Bastion
Host bastion1.usa.example.com
Host server*.usa.example.com
  ProxyCommand ssh -W %h:%p bastion1.usa.example.com

# Canada Bastion
Host bastion1.can.example.com
Host server*.can.example.com
  ProxyCommand ssh -W %h:%p bastion1.can.example.com

# Mexico Bastion
Host bastion1.mex.example.com
Host server*.mex.example.com
  ProxyCommand ssh -W %h:%p bastion1.mex.example.com

Obviously, this is an oversimplified example but I hope it helps to demonstrate the use case.

**Comment by pkittenis** [comment]
That use case is supported already. The one time password for bastion login would obviously need to be provided which means including some kind of user input for that part.

Eg:

```
hosts = ['server1.can.example.com', 'server2.can.example.com']

client = ParallelSSHClient(hosts, 
    proxy_host='bastion1.usa.example.com', 
    proxy_password='<one time bastion pass>')
```

Where `<one time bastion pass>` is the one time password token.

`proxy_host` is essentially ProxyCommand when the command is `ssh` but without the extra process and need for `ssh` binary. 

Since the functionality is different, however, it is not possible to use existing proxycommand configuration in `~/.ssh/config` to configure `proxy_host`. The equivalent would be `host_config` which does not support proxy configuration yet (#82).

**Comment by pkittenis** [comment]
Functionality supported already as above. Please watch #82 for host config proxy configuration.
