### ISSUE TITLE
Make sudo and shell quote/escaping behaviour consistent between native and paramiko clients

### ISSUE THREAD

**Issue by Shados** [ParallelSSH/parallel-ssh#112]
I don't think the `shell` arguments to `run_command` and `exec_command` make sense -- you cannot know _a priori, in general_ which shell the remote host is running by default, which means (among other things) that you do not know what its escaping and quoting rules are.

As such, there's no guarantee that the `run_command` fragment below -- given a user-supplied shell and command (let alone attempting to use `$SHELL`) -- makes any sense on the remote system:
```
if shell:
    _command += '%s "%s"' % (shell, command,)
else:
    _command += '$SHELL -c "%s"' % (command,)
```

You could assume the remote is always entirely POSIX-shell-compatible, but in reality there's two common classes of system where that won't be true: users of `fish`, and many embedded devices. I don't think this is the right level at which to deal with the shell, because the requirements are very specific to the caller. 

Consider: currently, specifying any of the `shell`, `sudo`, or `user` arguments in either function alters the semantics of the `command` argument, because now the caller has to shell-escape the command string, and the escaping requirements may vary from shell to shell.

**Comment by pkittenis** [comment]
Hi there,

What is described in last paragraph does not look accurate. The quoting of the command passed in was put in exactly so users would *not* have to shell-escape the command string and there is a test for that [behaviour](https://github.com/ParallelSSH/parallel-ssh/blob/master/tests/test_pssh_ssh2_client.py#L775). This may well not work with non-posix shells though, that is true.

Further more, how a command is run varies depending on the SSH library used. With paramiko, no shell is used at all unless a command like `$SHELL <..>` is run. Running something like `echo` with paramiko without explicitly running in a shell would result in command not found.

OTOH, libssh2 seems to always use the user's defined shell whether or not an interactive shell was requested. So it would make sense to remove the `$SHELL` prefix and command quoting on libssh2 only, but on paramiko it would result in a broken client. 

Can test that out and if tests pass it can be removed.

**Comment by Shados** [comment]
Apologies for the late response @pkittenis, I've been sick for the past few days. I've elaborated below on what I was attempting to explain earlier, and have put some general suggested changes first, the combination of which is hopefully clearer than what I wrote previously.

## General Issue
Both `run_command` and `exec_command` currently make problematic assumptions about the environment of the remote system; some of these are due to bugs, but even with those fixed the `shell`, `sudo`, and `user` arguments cannot be implemented in a way that is actually universal/generic across all remote systems. I suspect that the attempt to implement their functionality inside `run/exec_command` is what lead to some of the bugs.


## Suggestions
1) Remove the `shell`, `sudo`, and `user` arguments from `run_command` and `exec_command` and their callers where relevant, as well as removing all existing escaping and quoting mechanisms -- just pass the supplied command through as-is, because the caller is really the only one who can possibly know enough about the remote system to construct it appropriately.
2) Add helper functions for doing commonly-useful things like Bourne-compatible shell escaping and quoting, wrapping commands in `sudo` or `su`, etc.
3) Implement functions like `run_unix_command` and `exec_unix_command` (or `run_bourne_command`/`exec_bourne_command`, but I suspect this would be less intuitive to people) that behave like the current functions (but with fixes for some of the below issues, where possible), in order to make porting existing uses trivial, and use the helpers from suggestion 2 in them

Moving them into their own function(s) would also make it easier to cleanly implement variants of the functionality for other types of remote system.

## Specific Problems

### For the paramiko-backed `exec_command`

#### Quoting Issue
How a command is run *on the remote system* does not _not_ vary based on the client-side SSH library used; the OpenSSH server will _always_ use the remote user's shell to run a command given on an exec request (on Linux it determines what the shell is by checking user's passwd entry, possibly resolving it through NSS, and as far as I can tell you can't configure it at run-time to do otherwise). Other SSH daemons may do other things.

I would hazard a guess that you were seeing `command not found` for an `echo something` test when specifying `use_shell=False`, which would be because this results in (essentially) the following sequence of events:
    1. Internally, `command = 'echo something'`, `_command = '"%(command)s"'`
    2. This gets passed along to paramiko's `exec_command`, which starts a non-interactive, non-login ssh session to run the command -- the equivalent of `ssh user@host '"echo something"`
    3. OpenSSH's `sshd` starts the remote shell, here assumed to be a Bourne-compatible shell, and attempts to run the given exec string -- the equivalent of the following in bash or Bourne shell: `$ "echo something"`
    4. The command is not found, because the entire thing is quoted, meaning it gets passed in as a *single token* to the underlying shell, and of course there is no builtin function or binary in `$PATH` that happens to be called "echo something"

If the function weren't falling back to quoting the command string, it would work just fine because it would be correctly tokenized by the remote shell into two tokens (a command and an argument), and it would call the built-in echo function:
```
$ python
Python 3.6.4 (default, Dec 19 2017, 05:36:13)
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from paramiko import SSHClient, WarningPolicy
>>> sshc = SSHClient()
>>> sshc.set_missing_host_key_policy(WarningPolicy())
>>> sshc.connect('192.168.8.8', username='pssh_testing', port=54201)
/nix/store/5rkyjz5jbff55x6ssnfycgs3kh0vkha8-python3-3.6.4-env/lib/python3.6/site-packages/paramiko/client.py:682: UserWarning: Unknown ssh-rsa host key for [192.168.8.8]:54201: b'cfce84261b6671ceb8de9ac9521c00db'
  (key.get_name(), hostname, hexlify(key.get_fingerprint())))
>>> stdin, stdout, stderr = sshc.exec_command('echo --help')
>>> stdout.read()
b'--help\n'
>>>
```
vs:
```
>>> stdin, stdout, stderr = sshc.exec_command('"echo --help"')
>>> stdout.read()
b''
>>> stderr.read()
b'bash: echo --help: command not found\n'
>>>
```

Note: I used `echo --help` for the command string, because **if** the remote `echo` being used were a standalone binary rather than a shell builtin it would have actually printed out a help page rather than echoing `--help` back at me, e.g.:
```
shados@dreamlogic[/home/shados] λ ssh pssh_testing@s2 'echo --help'
--help
shados@dreamlogic[/home/shados] λ ssh pssh_testing@s2
[pssh_testing@home ~]$ echo --help
--help
[pssh_testing@home ~]$ /usr/bin/echo --help
Usage: /usr/bin/echo [SHORT-OPTION]... [STRING]...
  or:  /usr/bin/echo LONG-OPTION
Echo the STRING(s) to standard output.

  -n             do not output the trailing newline
  -e             enable interpretation of backslash escapes

...

  \xHH    byte with hexadecimal value HH (1 to 2 digits)

NOTE: your shell may have its own version of echo, which usually supersedes
the version described here.  Please refer to your shell's documentation
for details about the options it supports.

GNU coreutils online help: <https://www.gnu.org/software/coreutils/>
Full documentation at: <https://www.gnu.org/software/coreutils/echo>
or available locally via: info '(coreutils) echo invocation'
[pssh_testing@home ~]$
```


#### Escaping Issue
The [command escaping mechanism](https://github.com/ParallelSSH/parallel-ssh/blob/db0de23b77dfc95da10075cb05f3d2cc43c29156/pssh/ssh_client.py#L277-L278) is also problematic:
- It assumes both that the remote shell will be a Bourne-compatible shell, *and* that the command string is intended to be passed as a single token to another command (a specified shell or sudo), because otherwise you probably would want the command string to be unescaped so that it would be interpreted by the remote shell.  
You may want some part of the command string to be unescaped even if you are passing it to another shell -- you may want variables that only exist in the user's default shell substituted in, for example.
- There's no way to disable it, making the function incompatible with any device or configuration that isn't serving a Bourne-compatible shell on the remote end.
- I'm also not entirely confident that it is escaping properly, but I admit I haven't given it enough thought or testing to be sure either way. That said, Python 3.3 added `shlex.quote`, and it is [small/simple enough](https://github.com/python/cpython/blob/61eda7260ac9fcdb6c5f066eb48dc344544bdfa6/Lib/shlex.py#L308-L319) to reasonbly add to parallel-ssh if you do want to include Bourne-compatible shell escaping in the library.

### For the Native Client's `run_command`
If none of `sudo`, `user`, or `shell` are specified then the command string is [passed through completely unmodified (not quoted)](https://github.com/ParallelSSH/parallel-ssh/blob/db0de23b77dfc95da10075cb05f3d2cc43c29156/pssh/ssh2_client.py#L359-L370), which is fine.

But:
1) If any of them are specified then the command will take the form `%(shell)s '%(command)s'` or `sudo -u %(user)s -S %(shell)s '%(command)s'`, this essentially makes use of those arguments incompatible with any devices or configurations that do not support Bourne-compatible quoting syntax, or that only have `su` and not `sudo` (if you don't need to supply a password, `su` also works just fine in non-interactive ssh session).
The user could implement this themselves by preparing an appropriate `command` and avoiding these arguments, but then why advertise the functionality at the level of this function instead of on another more specific one, or as command-formatting/wrapping helper functions?
2) If `sudo` is specified and `shell` is not, you should pass `-s` to `sudo` instead of using `$SHELL` as the command -- it is a little more robust, as if `$SHELL` is not set it will look up the user's shell in the passwd database (on appropriately-configured Linux it will even resolve their passwd db entry via NSS).
3) It is not necessary to have `sudo` use a shell to run the command at all, you can just pass it the **unquoted** command to have `sudo` call it directly.
4) Unlike in the paramiko-backed `exec_command`, there's no attempt at escaping the passed command string -- this is not a problem in itself (I mean, the whole point I'm arguing is that escaping and quoting shouldn't be done at this level -- the caller may even want variables evaluated in the ssh user's shell, not the specified shell), but it's bizarre that the behaviour is inconsistent between the two functions.

**Comment by pkittenis** [comment]
Hi there,

Many thanks for the detailed feedback, much appreciated. In general, I would agree with your points. 

However, I think it is important to understand the reasoning behind having these features.

The point is for the client side code to be able to say:

```
client.run_command('touch /root/blah', sudo=True)
```

And have the command executed correctly with sudo. Per documentation, the `sudo` keyword argument passes the command string to the `sudo` command, subject to quoting in order to execute correctly. There is always the option of not using the sudo keyword and writing a complete command string client side.

The expectation from the client's POV is that anything that works sans sudo will work with it. Meaning this:

```
client.run_command('for i in 1 2 3; echo $i; done')
```

and this:

```
client.run_command('for i in 1 2 3; echo $i; done', sudo=True)
```

Need to
* have same output
* not need different command string for sudo and no sudo
* not have to quote or escape command string for sudo when it is not required for non-sudo

This enables ease of use for the vast majority of use cases that are 

* Using a POSIX  shell
* Want to run their command with sudo

There are of course edge cases where this is not suitable, like non-posix shells, embedded devices etc. For those use cases, it is best to write a command string client side and use `use_shell=False` for paramiko and not use either sudo/user arguments for native client. 

As these features are useful to a large majority of users, myself included, it would not be appropriate to remove them. If they are not suitable for a particular use case, best to not use them.

For the specific issues raised:
1. Paramiko quoting.

Yes, this is true. I think the best thing would be to have it match behaviour with the native client and only quote the command string when running with `sudo`. This will mean `use_shell` can be removed. The quoting currently being used is accurate and is integration tested - see [variable substitution](https://github.com/ParallelSSH/parallel-ssh/blob/master/tests/test_pssh_client.py#L675), [backticks](https://github.com/ParallelSSH/parallel-ssh/blob/master/tests/test_pssh_client.py#L793), [escaped commands](https://github.com/ParallelSSH/parallel-ssh/blob/master/tests/test_pssh_client.py#L813), [single quotes](https://github.com/ParallelSSH/parallel-ssh/blob/master/tests/test_pssh_client.py#L779) etc tests.

2. Separate functions for bourne/posix shells.

No, I am not in favour or adding separate functions for posix/bourne shells. Can already send command strings as-is with the native client which is preferred. The by-default command escaping of the paramiko client will be removed as per 1.

3. "this essentially makes use of those arguments incompatible with any devices or configurations that do not support Bourne-compatible quoting syntax, or that only have su and not sudo"

That is ok. Again, these are convenience features for the majority of use cases they are suited to. Best not to use them otherwise. If you know you do not have sudo, need to do something special to use sudo or prefer to use `su` can always generate and/or escape the command string needed client side.

4. "If sudo is specified and shell is not, you should pass -s to sudo"

That breaks shell variables, multiple dependent commands, quoting, backticks, sub shells etc etc. See `sudo(8)` man page.

```
sudo -s for i in 1 2 3; echo $i; done
bash: syntax error near unexpected token `done'
sudo -s 'for i in 1 2 3; echo $i; done'
/bin/bash: for i in 1 2 3; echo ; done: command not found
sudo -s "for i in 1 2 3; echo $i; done"
/bin/bash: for i in 1 2 3; echo ; done: command not found
```

Example from man page:
```
sudo -s cd ~; ls -lh | sort -r > listing
(cd is not applied to rest of commands)
sudo sh -c "cd ~; ls -lh | sort -r > listing"
(this works correctly)
```

5. "It is not necessary to have sudo use a shell to run the command at all"

Does not work for anything that is not a simple command string - see above.

6. Inconsistent behaviour. 

Yes, this will be resolved. From further testing, there is no inconsistent behaviour in paramiko that requires quoting/escaping as long as sudo is not used.

**Comment by Shados** [comment]
OK, sounds perfectly reasonable to want to have the posix/bourne shell assumption as a default. As long as there's a way to pass exactly what I supply to the remote shell, and the usage is consistent across both clients, I'll be happy (my usage for parallel-ssh does actually happen to involve running things on a varied bunch of embedded devices).

**Comment by pkittenis** [comment]
Paramiko is deprecated and scheduled to be removed in `2.0.0`
