### ISSUE TITLE
ssh-python with libssh backend

### ISSUE THREAD

**Issue by Jakuje** [ParallelSSH/parallel-ssh#131]
Hello,
I see you work on the [ssh-python](https://github.com/ParallelSSH/ssh-python) with libssh, but I did not find any reference how or when parallel-ssh can be used with ssh-python. We would be interested in using it. Do you have expected timeframe when this is planed to be working?

**Comment by pkittenis** [comment]
Hi there,

Thanks for the interest. Yes, I am interested also and it is the plan to provide a libssh back-end to parallel-ssh. There is no time frame for this, depends on available free time. Can only suggest to see typical pattern for new releases. 

New client would show up in `1.10` as a base implementation, meaning auth and `run_command`. From working on `ssh-python`, libssh is also not fully non-blocking, some parts cannot be used at all for example scp and to an extent, connect, though provided sockets should be ok. So some features will not be possible without changes to upstream.

There will be a `[WIP]` PR up when the implementation starts. Contributions always welcome of course. 

The first steps are to finish up `ssh-python`, specifically wheels and windows support. A lot of that can be ported over from `ssh2-python` since dependencies are similar.

**Comment by pkittenis** [comment]
Have [created a project](https://github.com/ParallelSSH/parallel-ssh/projects) to track the libssh implementation to-do items. 

Please watch #135 on when the parallel client will be ready to use.
