### ISSUE TITLE
Native Tunnel implementation.

### ISSUE THREAD

**Issue by teucrus** [ParallelSSH/parallel-ssh#146]
Hello,

I want to have a portforward tunnel with simiral behaviour as ssh -L command. I tried to use Native Tunnel as per: https://parallel-ssh.readthedocs.io/en/latest/tunnel.html but I wasn't able to get much.

My code is the floowing:

```
from pssh.clients.native.tunnel import Tunnel
from collections import deque
in_q=deque()
out_q=deque()
routers="a dict with routers"
for router in routers.values():
    in_q.append((router.ip,22))
    tunnel=Tunnel(ip,in_q,out_q,port=22,user=username,password=password)
```

I don't get any errors, but the our_q is always empty. Also what is the expected behaviour for the tunnel. How would I connect to the tunneled devices?

I tried printing the out_q and tunnel. out_q is always empty. tunnel is <Tunnel(Thread-1, initial)> and tunnel_open is <threading.Event object at 0x00000167F51EDE80> 

Am assuming something wrong here?

Thank you.

**Comment by pkittenis** [comment]
Hi there,

Thanks for the interest!

This is better asked on the [mail group](https://groups.google.com/forum/#!forum/parallelssh) - issues tracker is for bugs with the code or feature requests.

The `Tunnel` class is a `threading.Thread` sub-class and implements direct-tcp/ip proxy connections to other SSH servers - it does not do port forwarding. I do not know if it can work for your use case.

Best way to see how to use it is with [existing code in the parallel client](https://github.com/ParallelSSH/parallel-ssh/blob/master/pssh/clients/native/parallel.py#L325-L345). Once a tunnel to an intermediate SSH server is active, it can be instructed to connect to `(host, port)` destinations from that server. Once connected [it then presents a port back](https://github.com/ParallelSSH/parallel-ssh/blob/master/pssh/clients/native/parallel.py#L357-L376) via `out_q` that can be connected on via `127.0.0.1:<port from out q>` on the local host running the tunnel. 

This is only needed if the remote `(host, port)` destinations are not accessible directly, otherwise there is no point in going through an SSH server. Ie, the router ips are only accessible via an SSH server running on `ip`. In that case, yes, the tunnel class can be used to present local ports to connect to them via the intermediate SSH server at `ip`.

For implementing port forwarding would need to use [ssh2-python forward listen](https://ssh2-python.readthedocs.io/en/latest/session.html#ssh2.session.Session.forward_listen_ex) directly. There is an [example for the C library here](https://libssh2.org/examples/tcpip-forward.html).

Have [posted this on the group ](https://groups.google.com/forum/#!topic/parallelssh/1D5TdQcxPdY)for any further discussion.
