### ISSUE TITLE
pssh.clients.native.single:scp_send requires sftp when not necessary i.e. when the remote directory exists

### ISSUE THREAD

**Issue by sanga** [ParallelSSH/parallel-ssh#157]
https://github.com/ParallelSSH/parallel-ssh/blob/379b8713fa79592b7e45ee4c9b8715efa36e525e/pssh/clients/native/single.py#L775

^ There we are checking if we're copying to a directory, however in the case that we're copying to a remote directory but that directory already exists - we will unnecessarily require sftp.

To work around this we need to use the private `_scp_send` method as when working with for example dropbear you don't have sftp (but of course the scp still works just fine as no remote dir needs to be created).

What might be a solution here? Just try, and create the sftp (or fail in the case the the remote sshd doesn't support it) in the case the directory creation was required?

**Comment by sanga** [comment]
Actually, further to this, in the case where SFTP isn't supported it'll currently just block forever. I guess it's spinning in `eagain` perhaps

**Comment by sanga** [comment]
excuse me. It's spinning in `_make_sftp` actually

**Comment by pkittenis** [comment]
Hi there,

Thanks for the interest. For reporting issues, code to reproduce the issue is needed. The issue template asks:

__Steps to reproduce:__

1. Example code that produces error.
2. Stack trace or error messages.

The documentation further states that SFTP is required when recurse is enabled. Can't say if that is the case here without code to reproduce.

**Comment by sanga** [comment]
Well, I can post some cost to reproduce, but the problem is that you'll need to test against a non-sftp ssh server (e.g. dropbear). Is that feasible?

**Comment by pkittenis** [comment]
SFTP can be disabled in config.. The point is it is expected that SFTP is required when recurse is enabled. Without code, I cannot say this is what is happening. The obvious answer if so is do not use recurse.

**Comment by sanga** [comment]
See the code from master below with comments inline.

I'm running:

```
client.scp_send('config', '/etc/config')
```

```
    def scp_send(self, local_file, remote_file, recurse=False, sftp=None):
        # local_file is a file so this if/else is skipped
        if os.path.isdir(local_file) and recurse:
            sftp = self._make_sftp() if sftp is None else sftp
            return self._scp_send_dir(local_file, remote_file, sftp)
        elif os.path.isdir(local_file) and not recurse:
            raise ValueError("Recurse must be True if local_file is a "
                             "directory.")
        destination = self._remote_paths_split(remote_file)
        # destination returns "/etc"
        if destination is not None:
            # so we now try to create an sftp object, despite the fact that sftp is disabled
            # which fails, retries, fails etc, ad infinitum
            # but /etc already exists so we don't actually need the sftp object
            # i.e. we don't need to create the remote directory
            sftp = self._make_sftp() if sftp is None else sftp
            try:
                self._eagain(sftp.stat, destination)
            except (SFTPHandleError, SFTPProtocolError):
                self.mkdir(sftp, destination)
self._scp_send(local_file, remote_file)
```

Is that clearer?

**Comment by pkittenis** [comment]
The client code executed is what was needed, thanks.

It looks like it should have the same `and recurse` check in the `if destination is not None` check that it does for local file. The code above is checking that the remote dir exists, which needs sftp for `stat`. But that should not be happening when recurse is off as that is the only case where the remote dir would be created regardless if it exists or not. In fact the whole `remote_paths_split` plus if block can go under an `if recurse` check.

On a separate note, the code should give up eventually when sftp is unavailable rather than hanging indefinitely - one for a separate issue.

It's a simple enough change for a PR if willing.
