### ISSUE TITLE
How do I grace kill a running command or script

### ISSUE THREAD

**Issue by boylegu** [ParallelSSH/parallel-ssh#168]
Due to the asynchronous. mybe can't get pid, so how do I grace kill a running command or script ？

**Comment by pkittenis** [comment]
Hi there,

Thanks for the interest. For usage questions use the [user's group](https://groups.google.com/forum/#!forum/parallelssh), this is an issue tracker.

This largely depends on the system, shell used and so on - there is no functionality in SSH protocol to monitor remote processes. When a PTY is used (`use_pty=True`), disconnecting the client also terminates the remote command as a side effect. Otherwise wrapper scripts can be used which are outside the scope of an SSH library.
