### ISSUE TITLE
Accounts daemon & indicator services using 100% CPU

### ISSUE THREAD

**Issue by Nagivarra** [ParallelSSH/parallel-ssh#169]
I am creating SSH connections between different hosts & Using SSH connection reading information from remote machine. while executing this commands in ssh from python code, remote side accounts-daemon & all indicator services are waking up & eating all CPU, causes other process die.
Why accounts-daemon & indicator services appear ?
How to control them ?
Please help me ...

Thanks in Advance
Regards
Nagendar

**Comment by pkittenis** [comment]
Hi there,

Thanks for the interest. This does not look like an issue with the library since it is a question about remote commands on server. I'd imagine same thing happens when running them locally. Best to ask system admin.

For reporting issues with the library please use issue template. At least code to reproduce an issue that only happens when using the library is needed.
