### ISSUE TITLE
[Feature Request] Add proxy_user and proxy_pkey to Native Single Host Client

### ISSUE THREAD

**Issue by maxballenger** [ParallelSSH/parallel-ssh#229]
It looks like the Native Single Host Client does not support the `proxy_user` and `proxy_pkey` inputs for initialization with a proxy host. The Native Parallel Client does. I have observed this in the below:
- https://parallel-ssh.readthedocs.io/en/latest/native_single.html
- https://parallel-ssh.readthedocs.io/en/latest/native_parallel.html
- Tested putting these options into the single host client `__init__()` using the version 1.9.1 of `parallel-ssh`

I have a use case with a proxy host that requires a different username and private key from the final host. I have been able to get this working using the parallel client's `proxy_user` and `proxy_pkey` `__init__()` inputs, but the parallel client provides a lot of functionality that is not necessary for this application where there is only a single endpoint host. I would like to standardize on `parallel-ssh` for the Python SSH library across a project with a few different developers. The additional complexity of the interface with a single host using the parallel client is undesirable for the rest of the group. It would help me make the case if I could use the single host client for this task.

I'd appreciate any feedback about how difficult this would be to add or any tips on how to achieve my goal another way, perhaps with an Agent or a Tunnel. Thanks!

**Comment by pkittenis** [comment]
Thanks for the interest and report.

Currently proxy/tunneling is implemented on the parallel client rather than each individual SSHClient. This means there can only be one proxy host, and an SSHClient cannot configure its own proxy.

In essence this request is the same as #82 and is also blocked by #140.

The tunneling implementation needs work in short, and is my priority once 2.0.0 final is released (RCs are out now).

It's quite a bit of work as it requires an almost re-write of the tunnel code, but is the next significant piece of work that I am prioritising.

**Comment by maxballenger** [comment]
Thank you for your response! Looking forward to it!

**Comment by pkittenis** [comment]
Done in `2.2.0`.
